name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6.2
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.2
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Deploy to heroku
        uses: akhileshns/heroku-deploy@v3.0.0
        with:
          buildpack: python
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name:  library-of-reading-tips
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          procfile: poetry run flask run
          
